version: '3.8'

services:
  auth_service:
    build: ./auth_service
    container_name: auth_service
    networks:
      - app-network
    ports:
      - "50051:50051"
    depends_on:
      - kafka_service

  gateway:
    build: ./gateway
    container_name: gateway
    networks:
      - app-network
    ports:
      - "8080:8080"
    depends_on:
      - auth_service
      - order_service
      - sales_service
      - warehouse_service

  notification_service:
    build: ./notification_service
    container_name: notification_service
    networks:
      - app-network
    depends_on:
      - kafka_service

  order_service:
    build: ./order_service
    container_name: order_service
    networks:
      - app-network
    ports:
      - "50052:50052"
    depends_on:
      - kafka_service
      - auth_service

  sales_service:
    build: ./sales_service
    container_name: sales_service
    networks:
      - app-network
    ports:
      - "50053:50053"
    depends_on:
      - kafka_service
      - warehouse_service

  warehouse_service:
    build: ./warehouse_service
    container_name: warehouse_service
    networks:
      - app-network
    ports:
      - "50054:50054"
    depends_on:
      - kafka_service

  kafka_service:
    container_name: kafka_service
    image: bitnami/kafka:latest
    networks:
      - app-network
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

